packages:
  - apps/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - prisma
  - unrs-resolver
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  prisma: true
  unrs-resolver: true
