'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { api, ApiError, saveTokens } from '../lib/api';

export function AuthForm({ mode }: { mode: 'login' | 'register' }) {
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get('password')); if (password.length < 12) return setError('Password must be at least 12 characters.'); setLoading(true); setError(''); try { const tokens = mode === 'login' ? await api.login(String(form.get('email')), password) : await api.register({ email: String(form.get('email')), firstName: String(form.get('firstName')), lastName: String(form.get('lastName')), password }); saveTokens(tokens); window.location.assign('/dashboard'); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Unable to continue.'); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="space-y-4 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">{mode === 'register' && <div className="grid grid-cols-2 gap-3"><Input name="firstName" label="First name" /><Input name="lastName" label="Last name" /></div>}<Input name="email" label="Email" type="email" /><Input name="password" label="Password" type="password" /><p className="text-xs text-slate-500">Use at least 12 characters.</p>{error && <p className="text-sm text-red-600">{error}</p>}<button disabled={loading} className="w-full rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white disabled:opacity-60">{loading ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button><p className="text-center text-sm text-slate-600">{mode === 'login' ? 'New here?' : 'Already registered?'} <Link className="font-semibold text-blue-700" href={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Create an account' : 'Sign in'}</Link></p></form>;
}
function Input({ name, label, type = 'text' }: { name: string; label: string; type?: string }) { return <label className="block text-sm font-medium text-slate-700">{label}<input required name={name} type={type} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5 outline-none focus:border-blue-600" /></label>; }
