ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'PROFILE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'SESSION_REVOKED';

ALTER TABLE "RefreshToken"
ADD COLUMN "userAgent" VARCHAR(255),
ADD COLUMN "ipAddress" VARCHAR(64);
